# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/oled_constraint.xdc

# Block Designs: bd/OLED_test/OLED_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLED_test || ORIG_REF_NAME==OLED_test} -quiet] -quiet

# IP: bd/OLED_test/ip/OLED_test_oledCtrl_test_0_0/OLED_test_oledCtrl_test_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OLED_test_oledCtrl_test_0_0 || ORIG_REF_NAME==OLED_test_oledCtrl_test_0_0} -quiet] -quiet

# XDC: f:/Xilinx/Project/FFT_OLED/FFT_OLED/FFT_OLED.gen/sources_1/bd/OLED_test/OLED_test_ooc.xdc
