webtalk_init -webtalk_dir F:/Xilinx/Project/FFT_OLED/FFT_OLED/FFT_OLED.sim/sim_1/behav/xsim/xsim.dir/oledCtrl_test_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May 10 00:03:08 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212201437_0_0_806" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f5730259-526b-4ae8-9d23-1c79621aad9a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a683cdb9329249aab0cc4c38cd98c736" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 1700X Eight-Core Processor         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "171328343 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "106.89_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14516_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4155059226 -regid "212201437_0_0_806" -xml F:/Xilinx/Project/FFT_OLED/FFT_OLED/FFT_OLED.sim/sim_1/behav/xsim/xsim.dir/oledCtrl_test_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/Xilinx/Project/FFT_OLED/FFT_OLED/FFT_OLED.sim/sim_1/behav/xsim/xsim.dir/oledCtrl_test_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/Xilinx/Project/FFT_OLED/FFT_OLED/FFT_OLED.sim/sim_1/behav/xsim/xsim.dir/oledCtrl_test_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
