@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< 646da2cf1faef1427dfaedfeca3ef2991c497034
REM Generated by Vivado on Sat May 08 17:28:42 -0500 2021
=======
REM Generated by Vivado on Sun May 09 23:37:38 -0500 2021
>>>>>>> OLED ctrl
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
REM compile Verilog/System Verilog design sources
<<<<<<< 646da2cf1faef1427dfaedfeca3ef2991c497034
echo "xvlog --incr --relax -L uvm -prj debouncer_tb_vlog.prj"
call xvlog  --incr --relax -L uvm -prj debouncer_tb_vlog.prj -log xvlog.log
=======
echo "xvlog --incr --relax -L uvm -prj oledCtrl_test_tb_vlog.prj"
call xvlog  --incr --relax -L uvm -prj oledCtrl_test_tb_vlog.prj -log xvlog.log
>>>>>>> OLED ctrl
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
