@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< 646da2cf1faef1427dfaedfeca3ef2991c497034
REM Generated by Vivado on Sat May 08 17:28:44 -0500 2021
=======
REM Generated by Vivado on Sun May 09 23:37:40 -0500 2021
>>>>>>> OLED ctrl
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
<<<<<<< 646da2cf1faef1427dfaedfeca3ef2991c497034
echo "xelab -wto a683cdb9329249aab0cc4c38cd98c736 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot debouncer_tb_behav xil_defaultlib.debouncer_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto a683cdb9329249aab0cc4c38cd98c736 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot debouncer_tb_behav xil_defaultlib.debouncer_tb xil_defaultlib.glbl -log elaborate.log
=======
echo "xelab -wto a683cdb9329249aab0cc4c38cd98c736 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot oledCtrl_test_tb_behav xil_defaultlib.oledCtrl_test_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto a683cdb9329249aab0cc4c38cd98c736 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot oledCtrl_test_tb_behav xil_defaultlib.oledCtrl_test_tb xil_defaultlib.glbl -log elaborate.log
>>>>>>> OLED ctrl
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
