@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< 646da2cf1faef1427dfaedfeca3ef2991c497034
REM Generated by Vivado on Sat May 08 17:28:46 -0500 2021
=======
REM Generated by Vivado on Sun May 09 23:36:07 -0500 2021
>>>>>>> OLED ctrl
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
<<<<<<< 646da2cf1faef1427dfaedfeca3ef2991c497034
echo "xsim debouncer_tb_behav -key {Behavioral:sim_1:Functional:debouncer_tb} -tclbatch debouncer_tb.tcl -log simulate.log"
call xsim  debouncer_tb_behav -key {Behavioral:sim_1:Functional:debouncer_tb} -tclbatch debouncer_tb.tcl -log simulate.log
=======
echo "xsim oledCtrl_test_tb_behav -key {Behavioral:sim_1:Functional:oledCtrl_test_tb} -tclbatch oledCtrl_test_tb.tcl -log simulate.log"
call xsim  oledCtrl_test_tb_behav -key {Behavioral:sim_1:Functional:oledCtrl_test_tb} -tclbatch oledCtrl_test_tb.tcl -log simulate.log
>>>>>>> OLED ctrl
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
